unit:
    tc_folder : /test/unit/
    selector  : '*.t'
    regexp    : '.*/(?<testcase>.*?)\s+\.{2,}\s+(?<result>\w+)'
    env:
        HARNESS_OPTIONS       : 'j4:c'
        HARNESS_TIMER         : 1
        HARNESS_PERL_SWITCHES : '-MDevel::Cover=-db,cover_db'

coverage:
    exec      : cover -report html


