BEGIN TRANSACTION;
CREATE TABLE `userphonenumber` (
	`UserPhoneNumberID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`PhoneNumberID`	INTEGER NOT NULL,
	`UserID`	INTEGER NOT NULL
);
CREATE TABLE `user` (
	`UserID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Email`	TEXT UNIQUE,
	`LastName`	TEXT,
	`ForName`	TEXT
);
CREATE TABLE `phonenumber` (
	`PhoneNumberID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`PhoneNumber`	TEXT NOT NULL
);
COMMIT;
